
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld
  namespace: flex-system
spec:
  interval: 1m
  url: ssh://github.com/kovpe/tf-controller-helloworld
  ref:
    branch: main
  secretRef: 
    name: github-ssh
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld
  namespace: flex-system
spec:
  path: ./terraform
  approvePlan: auto
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flex-system
  writeOutputsToSecret:
    name: helloworld-outputs
