---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld-tf
  namespace: test
spec:
  interval: 1m
  url: ssh://github.com/kovpe/tf-controller-helloworld
  ref:
    branch: main
  secretRef: github-ssh
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
  namespace: test
spec:
  path: ./terraform
  approvePlan: auto
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
    namespace: test
  writeOutputsToSecret:
    name: helloworld-outputs
